### PR TITLE
Better placeholder for creator avatar alt text

### PR DESCRIPTION
**Pull request by montsamu**
#23

### CODE REVIEW

**Comment by nieldlr** [comment]
Heya @montsamu, this is looking perfect. Thanks so much for this! 👌

I'm still trying to figure out the right process here. For now, I'm going to roll with the usual process here. I noticed you haven't quite done the bundling yet. Would you be for running `npm run build` & committing the build files to this PR?

Thanks again!

**Comment by montsamu** [comment]
It's a bit of a mess with my build output here; IMHO builds should not be in the same git as the source, but I've definitely been wrong before. For example, this official react project includes "build/" in the .gitignore:

https://github.com/facebook/react-native/blob/v0.2.1/Examples/SampleApp/.gitignore

But maybe? that's because it's a "native" project; I don't know quite enough there.

**Comment by nieldlr** [comment]
Heya @montsamu,

you're completely right there. This was a hack on my side to get things rolling. I did some research & realized we could do the build on deploy instead. (I'm hosting on Heroku atm).

I had to roll this PR into my branch locally to remove the ./build files from the PR + repo. Check it out here #36. Thanks so much for this! And also fixing those other bugs too. 👌

**Comment by montsamu** [comment]
Absolutely! And another way to deal with "builds" (to reduce deployment time) is to create branches for builds, and go ahead and check builds in there; but as long as Heroku "build on deploy" is working, that should be fine, too!

**Pull request merged**
